name: "MacPorts for gh actions"
description: "A GitHub Action that facilitates using MacPorts."
author: "David Chavez<david@dcvz.io>"
inputs:
  version:
    description: "The version of MacPorts to use (must be above 2.8.0)"
    required: false
    default: "2.8.0"
  dependencies:
    description: "The dependencies to install"
    required: false
    default: "[]"
runs:
  using: "node16"
  main: "dist/install/index.js"
branding:
  icon: "archive"
  color: "gray-dark"